Repository include-us/Face-Mask-Detection-Attendance-System, pull requests merged in 2021-03, with the labels that each got.

#8 Barcode module updated
  barcode/barcode.py
Labels: enhancement

#9 barcode module prepped
  barcode/barcode.py
  main.py
  mask_detection.py
Labels: enhancement

#10 major bug - same methods got redefined
  barcode/barcode.py
Labels: bug

#21 Data for testing
  .gitignore
  attendance/data.csv
  temp.jpg
Labels: documentation

#26 facemask bug fix
  attendance/data.csv
  facemask/facemask.py
  temp.jpg
Labels: bug

#30 Closing Action Added
  windows/open_panel.py
Labels: enhancement
